# Generated by Django 6.0 on 2026-03-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Entrega estimada'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_type',
            field=models.CharField(choices=[('contra_entrega', 'Pago contra entrega'), ('consignacion', 'Consignación'), ('transferencia', 'Transferencia')], default='contra_entrega', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Productor o finca'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_type',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('recoger', 'Recoger en tienda')], default='domicilio', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('gr', 'Gramo'), ('lb', 'Libra')], default='kg', max_length=10),
        ),
    ]
