# Generated by Django 6.0 on 2026-03-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_delivery_time_product_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(choices=[('24h', '24 horas dentro del municipio'), ('48h', '24 a 48 horas'), ('3dias', '2 a 3 días hábiles'), ('5dias', '3 a 5 días hábiles')], default='24h', max_length=20, verbose_name='Entrega estimada'),
        ),
    ]
