# Generated by Django 6.0 on 2026-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('und', 'Unidad'), ('lb', 'Libra')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo')], default='kg', max_length=10),
        ),
    ]
