# Generated by Django 6.0 on 2026-03-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unit_alter_product_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra')], default='kg', max_length=10),
        ),
    ]
