# Generated by Django 6.0 on 2026-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('identificacion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('solicitud', models.CharField(choices=[('informacion', 'Consultas sobre productos'), ('queja', 'Atencion al cliente'), ('reclamo', 'Quejas o Reclamos'), ('otro', 'Otro')], max_length=20)),
                ('asunto', models.CharField(max_length=160)),
                ('mensaje', models.TextField()),
                ('contacto', models.CharField(choices=[('correo', 'Correo electrónico'), ('whatsapp', 'Whatsapp')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('honeypot', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
